### ISSUE TITLE
 ClientSocket.cpp:121:17: error: 'close' was not declared in this scope

### ISSUE THREAD

**Issue by tseemann** [HIITMetagenomics/dsm-framework#1]
I'm getting this compile failure on both g++ 4.7 and 5.3 for current HEAD 

```
g++  -Wall -Iincbwt/ -Ilibcds/includes/ -g -DMASSIVE_DATA_RLCSA -DPARALLEL_SUPPORT -fopenmp -std=c++0x -O3 -DNDEBUG  -c -o ClientSocket.o ClientSocket.cpp
ClientSocket.cpp: In destructor 'virtual ClientSocket::~ClientSocket()':
ClientSocket.cpp:121:17: error: 'close' was not declared in this scope
     close(sockfd);
                 ^
```

**Comment by andersgs** [comment]
I was able to get it to compile by adding the following header call to ClientSocket.cpp:

    #include <unistd.h>

Based on the following: 
http://stackoverflow.com/questions/14575068/close-function-not-being-recognized-c
http://stackoverflow.com/questions/12159732/arm-cross-compilation-error-using-fcntl-h-error-close-was-not-declared-in-t
http://raspberrypi.stackexchange.com/questions/1745/problems-with-close-read-write-filedescriptors-while-cross-compiling-on-x86-l

**Comment by nvalimak** [comment]
Fixed it as andersgs suggested.

**Comment by tseemann** [comment]
Thanks Niko @nvalimak
